version: '3.1'
services:
  app:
    container_name: docker-whathappened
    image: whathappened
    build: ./
    ports:
      - "8085:8085"
    depends_on:
      - postgresqldb

  postgresqldb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD = 12345
      - POSTGRES_USER = postgres
      - POSTGRES_DB = pribas

